INSERT INTO ENDERECO (BAIRRO, CEP, CIDADE, COMPLEMENTO, ESTADO, LOGRADOURO, NUMERO) VALUES ('BAIRRO', '00000000', 'SAOPAULO', '1', 'SP', 'RUA QUALQUER', '123')
--INSERT INTO FINANCEIRA (CNPJ, EMAIL, NUMEROAGENCIA, NUMEROBANCO, NUMEROCONTA, SENHA, TELEFONE, ENDERECO_ID) VALUES ('1', 'a@a.com', '1', '1', '1', 'abc', '99999999', 1);
--CREATE TABLE A