INSERT INTO ENDERECO (BAIRRO, CEP, CIDADE, COMPLEMENTO, ESTADO, LOGRADOURO, NUMERO) VALUES ('BAIRRO', '00000000', 'SAOPAULO', '1', 'SP', 'RUA QUALQUER', '123');
INSERT INTO FINANCEIRA (CNPJ, EMAIL, NUMEROAGENCIA, NUMEROBANCO, NUMEROCONTA, SENHA, TELEFONE, ENDERECO_ID) VALUES ('123', 'a@a.com', '1', '1', '1', '123', '99999999', 1);
INSERT INTO SESSIONID (SESSION_ID) VALUES ('DEFAULT')

--THE TABLES NAMES NEEDS TO BE IN ALPHABETICAL ORDER TO WORK.